eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
#  endpoint:
#    health:
#      show-details: always
info:
  author: Vinicius R. Felce
  mail: viramos017@gmail.com
  cel: +55 11 96227-3095
server:
  port: ${PORT:9999}
message: Mensagem generica
